### ISSUE TITLE
Add Azure endpoint configurations for other clouds

### ISSUE THREAD

**Issue by yangl900** [Azure/aks-traffic-manager#1]
We only added public Azure cloud configuration. Should include other national clouds.

**Comment by xizha162** [comment]
Fixed in commit ccf0f3e946b72a77bcbd2745ae5e671fabe8048a. Added the coud environment config files for national clouds according to https://github.com/Azure/go-autorest/blob/master/autorest/azure/environments.go

**Comment by xizha162** [comment]
close the issue.
